"""empty message

Revision ID: ecab00a08f35
Revises: None
Create Date: 2016-02-20 23:53:26.607698

"""

# revision identifiers, used by Alembic.
revision = 'ecab00a08f35'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_path', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_path')
    ### end Alembic commands ###
